import io

p = r'crates/app/src/main.rs'
s = io.open(p, encoding='utf-8').read()

if 'ModelSelect' in s:
    print('already present')
else:
    # 1) Dialog variant
    a = 'enum Dialog {\n    RenameSession { value: String },\n}'
    n = 'enum Dialog {\n    RenameSession { value: String },\n    ModelSelect { filter: String },\n}'
    assert a in s
    s = s.replace(a, n, 1)

    # 2) fields
    a = '    commands: Vec<SlashCommand>,\n'
    assert a in s
    s = s.replace(a, a + '    available_models: Vec<pi_link::protocol::ModelInfo>,\n', 1)

    a = '            commands: Vec::new(),\n'
    assert a in s
    s = s.replace(a, a + '            available_models: Vec::new(),\n', 1)

    # 3) refresh_state pulls models
    a = '            let _ = session.send(&Command::GetCommands);\n'
    assert a in s
    s = s.replace(a, a + '            let _ = session.send(&Command::GetAvailableModels);\n', 1)

    # 4) response arm
    a = (
        '                } else if command == "get_commands" && success {\n'
        '                    if let Some(data) = &data {\n'
        '                        self.commands = SlashCommand::parse_list(data);\n'
        '                    }\n'
    )
    n = (
        '                } else if command == "get_commands" && success {\n'
        '                    if let Some(data) = &data {\n'
        '                        self.commands = SlashCommand::parse_list(data);\n'
        '                    }\n'
        '                } else if command == "get_available_models" && success {\n'
        '                    if let Some(data) = &data {\n'
        '                        self.available_models =\n'
        '                            pi_link::protocol::parse_model_list(data);\n'
        '                    }\n'
    )
    assert a in s
    s = s.replace(a, n, 1)

    # 5) select_model + cycle_thinking actions
    a = '    fn confirm_rename(&mut self, cx: &mut Context<Self>) {'
    n = (
        '    fn select_model(&mut self, provider: String, id: String, cx: &mut Context<Self>) {\n'
        '        if let Some(session) = &self.session {\n'
        '            let _ = session.send(&Command::SetModel {\n'
        '                provider,\n'
        '                model: id,\n'
        '            });\n'
        '        }\n'
        '        self.dialog = None;\n'
        '        self.refresh_state();\n'
        '        cx.notify();\n'
        '    }\n'
        '\n'
        '    fn cycle_thinking(&mut self, cx: &mut Context<Self>) {\n'
        '        const LEVELS: [&str; 7] =\n'
        '            ["off", "minimal", "low", "medium", "high", "xhigh", "max"];\n'
        '        let cur = self\n'
        '            .state\n'
        '            .as_ref()\n'
        '            .and_then(|s| s.thinking_level.clone())\n'
        '            .unwrap_or_else(|| "medium".into());\n'
        '        let idx = LEVELS.iter().position(|&l| l == cur).map(|i| i + 1).unwrap_or(0);\n'
        '        let next = LEVELS[idx % LEVELS.len()].to_string();\n'
        '        if let Some(session) = &self.session {\n'
        '            let _ = session.send(&Command::SetThinkingLevel { level: next.clone() });\n'
        '        }\n'
        '        self.refresh_state();\n'
        '        self.status = format!("thinking: {next}");\n'
        '        cx.notify();\n'
        '    }\n'
        '\n'
        '    fn confirm_rename(&mut self, cx: &mut Context<Self>) {'
    )
    assert a in s
    s = s.replace(a, n, 1)

    # 6) toolbar: model label clickable -> dialog; thinking label clickable -> cycle
    a = (
        '                                    .child(\n'
        '                                        div()\n'
        '                                            .flex()\n'
        '                                            .items_center()\n'
        '                                            .gap_1()\n'
        '                                            .child("\\u{2699}")\n'
        '                                            .child(model_label),\n'
        '                                    ),\n'
    )
    n = (
        '                                    .child(\n'
        '                                        div()\n'
        '                                            .id("model-select")\n'
        '                                            .flex()\n'
        '                                            .items_center()\n'
        '                                            .gap_1()\n'
        '                                            .cursor_pointer()\n'
        '                                            .hover(|s| s.text_color(rgb(t.text)))\n'
        '                                            .on_mouse_down(MouseButton::Left, {\n'
        '                                                let weak = weak_for_dialog.clone();\n'
        '                                                move |_, _, cx| {\n'
        '                                                    let _ = weak.update(cx, |c, cx| {\n'
        '                                                        if c.available_models.is_empty() {\n'
        '                                                            c.refresh_state();\n'
        '                                                        }\n'
        '                                                        c.dialog =\n'
        '                                                            Some(Dialog::ModelSelect {\n'
        '                                                                filter: String::new(),\n'
        '                                                            });\n'
        '                                                        cx.notify();\n'
        '                                                    });\n'
        '                                                }\n'
        '                                            })\n'
        '                                            .child("\\u{2699}")\n'
        '                                            .child(model_label),\n'
        '                                    ),\n'
    )
    assert a in s, 'model toolbar not found'
    s = s.replace(a, n, 1)

    a = (
        '                                    .child(format!("\\u{1f4a1} {thinking_label}"))\n'
    )
    n = (
        '                                    .child(\n'
        '                                        div()\n'
        '                                            .id("thinking-cycle")\n'
        '                                            .cursor_pointer()\n'
        '                                            .hover(|s| s.text_color(rgb(t.text)))\n'
        '                                            .on_mouse_down(MouseButton::Left, cx.listener(\n'
        '                                                |this, _: &gpui::MouseDownEvent, _w, cx| {\n'
        '                                                    this.cycle_thinking(cx);\n'
        '                                                },\n'
        '                                            ))\n'
        '                                            .child(format!("\\u{1f4a1} {thinking_label}")),\n'
        '                                    )\n'
    )
    assert a in s, 'thinking label not found'
    s = s.replace(a, n, 1)

    # 7) render_dialog: ModelSelect arm
    a = (
        '    fn render_dialog(&mut self, weak: &gpui::WeakEntity<Chat>, t: &theme::Theme) -> Option<gpui::AnyElement> {\n'
        '        let Dialog::RenameSession { value } = self.dialog.as_ref()?;'
    )
    n = (
        '    fn render_dialog(&mut self, weak: &gpui::WeakEntity<Chat>, t: &theme::Theme) -> Option<gpui::AnyElement> {\n'
        '        if let Dialog::ModelSelect { filter } = self.dialog.as_ref() {\n'
        '            let flt = filter.to_lowercase();\n'
        '            let mut rows: Vec<gpui::AnyElement> = Vec::new();\n'
        '            for (i, m) in self\n'
        '                .available_models\n'
        '                .iter()\n'
        '                .filter(|m| {\n'
        '                    flt.is_empty()\n'
        '                        || m.id.to_lowercase().contains(&flt)\n'
        '                        || m.name.to_lowercase().contains(&flt)\n'
        '                        || m.provider.to_lowercase().contains(&flt)\n'
        '                })\n'
        '                .take(12)\n'
        '            {\n'
        '                let provider = m.provider.clone();\n'
        '                let id = m.id.clone();\n'
    '                let weak_row = weak.clone();\n'
        '                let label: SharedString = format!("{} / {}", m.provider, m.label()).into();\n'
        '                let ctx: SharedString = m\n'
        '                    .context_window\n'
        '                    .map(|c| format!("{}k", c / 1000))\n'
        '                    .unwrap_or_default()\n'
        '                    .into();\n'
        '                rows.push(\n'
        '                    div()\n'
        '                        .id(SharedString::from(format!("model-{provider}-{id}")))\n'
        '                        .w_full()\n'
        '                        .px_3()\n'
        '                        .py_1p5()\n'
        '                        .cursor_pointer()\n'
        '                        .rounded_md()\n'
        '                        .hover(|s| s.bg(rgb(t.bg_selected)))\n'
        '                        .on_mouse_down(MouseButton::Left, move |_, _, cx| {\n'
        '                            let (p, mid) = (provider.clone(), id.clone());\n'
        '                            let _ = weak_row.update(cx, |c, cx| c.select_model(p, mid, cx));\n'
        '                        })\n'
        '                        .flex()\n'
        '                        .justify_between()\n'
        '                        .child(\n'
        '                            div().text_xs().text_color(rgb(t.text)).child(label),\n'
        '                        )\n'
        '                        .child(\n'
        '                            div().text_xs().text_color(rgb(t.text_dim)).child(ctx),\n'
        '                        ),\n'
        '                );\n'
        '            }\n'
        '            let list_panel = if rows.is_empty() {\n'
        '                div()\n'
        '                    .py_2()\n'
        '                    .text_xs()\n'
        '                    .text_color(rgb(t.text_dim))\n'
        '                    .child("no models match")\n'
        '                    .into_any_element()\n'
        '            } else {\n'
        '                div().flex().flex_col().gap_0p5().children(rows).into_any_element()\n'
        '            };\n'
        '            let weak_close = weak.clone();\n'
        '            let weak_f = weak.clone();\n'
        '            let filter_view: SharedString = if filter.is_empty() {\n'
        '                "filter models...".into()\n'
        '            } else {\n'
        '                filter.clone().into()\n'
        '            };\n'
        '            let filter_empty = filter.is_empty();\n'
        '            return Some(\n'
        '                div()\n'
        '                    .absolute()\n'
        '                    .inset_0()\n'
        '                    .bg(gpui::hsla(0., 0., 0., 0.35))\n'
        '                    .flex()\n'
        '                    .items_center()\n'
        '                    .justify_center()\n'
        '                    .child(\n'
        '                        div()\n'
        '                            .w(px(520.))\n'
        '                            .max_h(px(560.))\n'
        '                            .bg(rgb(t.bg_panel))\n'
        '                            .border_1()\n'
        '                            .border_color(rgb(t.border))\n'
        '                            .rounded_lg()\n'
        '                            .p_4()\n'
        '                            .flex()\n'
        '                            .flex_col()\n'
        '                            .gap_3()\n'
        '                            .shadow_lg()\n'
        '                            .child(\n'
        '                                div()\n'
        '                                    .flex()\n'
        '                                    .items_center()\n'
        '                                    .justify_between()\n'
        '                                    .child(\n'
        '                                        div()\n'
        '                                            .text_sm()\n'
        '                                            .font_weight(gpui::FontWeight::SEMIBOLD)\n'
        '                                            .text_color(rgb(t.text))\n'
        '                                            .child("select model"),\n'
        '                                    )\n'
        '                                    .child(\n'
        '                                        div()\n'
        '                                            .id("model-close")\n'
        '                                            .px_2()\n'
        '                                            .cursor_pointer()\n'
        '                                            .text_color(rgb(t.text_muted))\n'
        '                                            .hover(|s| s.text_color(rgb(t.text)))\n'
        '                                            .on_mouse_down(MouseButton::Left, move |_, _, cx| {\n'
        '                                                let _ = weak_close.update(cx, |c, cx| {\n'
        '                                                    c.dialog = None;\n'
        '                                                    cx.notify();\n'
        '                                                });\n'
        '                                            })\n'
        '                                            .child("\\u{00d7}"),\n'
        '                                    ),\n'
        '                            )\n'
        '                            .child(\n'
        '                                div()\n'
        '                                    .id("model-filter")\n'
        '                                    .track_focus(&self.dialog_focus)\n'
        '                                    .on_key_down({\n'
        '                                        let weak = weak_f.clone();\n'
        '                                        move |ev: &KeyDownEvent, _w, cx| {\n'
        '                                            let key = ev.keystroke.key.as_str();\n'
        '                                            let _ = weak.update(cx, |this, cx| {\n'
        '                                                if let Dialog::ModelSelect { filter } =\n'
        '                                                    &mut this.dialog\n'
        '                                                {\n'
        '                                                    match key {\n'
        '                                                        "escape" => {\n'
        '                                                            this.dialog = None;\n'
        '                                                            cx.notify();\n'
        '                                                        }\n'
        '                                                        "backspace" => {\n'
        '                                                            filter.pop();\n'
        '                                                            cx.notify();\n'
        '                                                        }\n'
        '                                                        "space" => {\n'
        '                                                            filter.push(\' \');\n'
        '                                                            cx.notify();\n'
        '                                                        }\n'
        '                                                        k => {\n'
        '                                                            if k.chars().count() == 1 {\n'
        "                                                                if let Some(c) = k.chars().next() {\n"
        '                                                                    filter.push(c);\n'
        '                                                                    cx.notify();\n'
        '                                                                }\n'
        '                                                            }\n'
        '                                                        }\n'
        '                                                    }\n'
        '                                                }\n'
        '                                            });\n'
        '                                        }\n'
        '                                    })\n'
        '                                    .px_2()\n'
        '                                    .py_1p5()\n'
        '                                    .rounded_md()\n'
        '                                    .border_1()\n'
        '                                    .border_color(rgb(t.border))\n'
        '                                    .bg(rgb(t.bg))\n'
        '                                    .text_xs()\n'
        '                                    .text_color(if filter_empty {\n'
        '                                        rgb(t.text_dim)\n'
        '                                    } else {\n'
        '                                        rgb(t.text)\n'
        '                                    })\n'
        '                                    .child(filter_view),\n'
        '                            )\n'
        '                            .child(list_panel),\n'
        '                    ),\n'
        '            );\n'
        '        }\n'
        '        let Dialog::RenameSession { value } = self.dialog.as_ref()?;'
    )
    assert a in s, 'render_dialog head not found'
    s = s.replace(a, n, 1)

    io.open(p, 'w', encoding='utf-8', newline='\n').write(s)
    print('model select ok')
